import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Navbar from "@/components/navbar";
import LegalGuide from "@/components/legalGuide";
import Image from "next/image";
import logo from "../../public/sakhi-logo.svg";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-full`}>
        <div className=" hidden md:flex z-10  justify-start   p-2 pt-0 rounded-b-lg items-center ml-20">
          <Image
            className=""
            src={logo}
            alt="Sakhi Logo"
            width={80}
            height={80}
          />
          <p className="text-3xl font-bold logo-font">Sakhi</p>
        </div>
        <div className="h-full w-full flex flex-row">
          <Navbar />
          <div className="flex-1 md:m-6">{children}</div>
          <Toaster />
          <LegalGuide />
        </div>
      </body>
    </html>
  );
}
